apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::000181800152:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::000181800152:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RCGCJ0QQWBQ6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T09:53:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2014"
  uid: aa8f54a0-d552-4a54-ab21-ab6748aab167
